services:
  - type: web
    name: store-rating-platform-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: store-rating-db
          property: connectionString
      - key: JWT_SECRET
        sync: false

databases:
  - name: store-rating-db
    databaseName: store_ratings_db
    plan: free
    ipAllowList: []
